//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaNegocio
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class AseguradoraBDEntities : DbContext
    {
        public AseguradoraBDEntities()
            : base("name=AseguradoraBDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<detalleSeguroObligatorio> detalleSeguroObligatorio { get; set; }
        public virtual DbSet<detalleSeguroTodoRiesgo> detalleSeguroTodoRiesgo { get; set; }
        public virtual DbSet<detalleSeguroVoluntario> detalleSeguroVoluntario { get; set; }
    
        public virtual ObjectResult<MostrarDetalleSegurosVehiculosCliente_Result> MostrarDetalleSegurosVehiculosCliente(Nullable<int> idCliente)
        {
            var idClienteParameter = idCliente.HasValue ?
                new ObjectParameter("idCliente", idCliente) :
                new ObjectParameter("idCliente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MostrarDetalleSegurosVehiculosCliente_Result>("MostrarDetalleSegurosVehiculosCliente", idClienteParameter);
        }
    }
}
